AWSTemplateFormatVersion: 2010-09-09
Description: "The Cf-Stack for the ecs-cluster"

Parameters:
  Stage:
    Type: String

Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub "${AWS::StackName}"
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}"
        - Key: "Stage"
          Value: !Sub "${Stage}"

Outputs:
  ECSClusterOutput:
    Description: The ecs-cluster arn
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub "${AWS::StackName}:ecsArn"
